[package]
name = "auto_tx"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
cloud-util = { package = "cloud-util", git = "https://github.com/cita-cloud/cloud-common-rs" }
common-rs = { git = "https://github.com/cita-cloud-cache/common-rs" }
cita_cloud_proto = { package = "cita_cloud_proto", git = "https://github.com/cita-cloud/cloud-common-rs" }

anyhow = "1.0"
axum = "0.6"
clap = { version = "4.4", features = ["derive"] }
once_cell = "1.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
hex = "0.4.3"
reqwest = { version = "0.11", features = ["json"] }
ethabi = "18.0.0"
prost = "0.11"
web3 = { git = "https://github.com/Jayanring/rust-web3" }
opendal = { version = "0.40", features = ["services-sled"] }
cita-tool = "0.21.1"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
