port = 3000
kms_url = "http://api.rivtower.cc/rivtrust-kms"
etcd_endpoints = [
    "127.0.0.1:2379",
]

#[cita_create_config]
#chain_name = ""
#create_url = ""
#accessid = ""
#access_secret = ""
#appid = ""
#appsecret = ""
#verify = ""
#dapp_name = ""

[service_register_config]
service_name = "auto_tx"
service_port = 3000
ttl = 60
tags = [
    "traefik/http/middlewares/cache-auto-tx-stripprefix/stripprefix/prefixes=/auto_tx",
    "traefik/http/routers/auto_tx/middlewares=cache-forward-auth,cache-auto-tx-stripprefix",
    "traefik/http/routers/auto_tx/rule=PathPrefix(`/auto_tx`) && (Headers(`version`, `latest`) || !HeadersRegexp(`version`, `.*?`))",
]

[log_config]
service_name = "auto_tx"
max_level = "info"
filter = "info"
# max_level = "debug"
# filter = "debug,hyper=info,opendal=info,sled=info,reqwest=info,h2=info,tower=info"
# rolling_file_path = "./logs"
# agent_endpoint = "127.0.0.1:6831"
