port = 80
data_dir = "/cita/api/data"
kms_url = "http://124.71.204.213/cache_kms/api/keys"

[consul_config]
consul_addr = "http://consul.rivtower.xyz"
service_name = "sap_auto_api"
service_id = "sap_auto_api_0"
service_address = "http://cita_api.hackathon.cn40.apps.platform.sapcloud.cn"
service_port = 80
tags = []
check_http_path = "/health"
check_interval = "10s"
check_timeout = "3s"
check_deregister_critical_service_after = "1m"

[log_config]
max_level = "info"
filter = "debug,hyper=info"
service_name = "auto-tx"
